version: '3.8'

services:
  # 1. The Core AI & API Platform
  plight_backend:
    build: 
      context: ./backend  # <-- Points Docker to the new backend subfolder
      dockerfile: Dockerfile
    container_name: plight_gateway
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://plight_mongo:27017/
    depends_on:
      - plight_mongo
    volumes:
      - ./backend/exports:/app/exports # Maps local folder to container

  # 2. The DSR-CRAG Ground Truth Database
  plight_mongo:
    image: mongo:latest
    container_name: plight_database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
