// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snxmttafmbgkspehlqoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNueG10dGFmbWJna3NwZWhscW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTY3NTQsImV4cCI6MjA2NTczMjc1NH0.XxO6wMZbF9RAxLnTBbOtjexx9waeQ7ImjQiCQtm6h5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);